### PR TITLE
ci: a run on main is never cancelled — the merge that lands must be built and shippable

### LINKED ISSUE #2412: No CI run builds the combination that lands: a merge burst ships semantic conflicts untested
## The gap

**No CI run ever builds the combination that lands.** With `strict: false` (correct, and not what I am proposing to change) a PR is tested against the `main` it branched from. Merge several in quick succession and the tree that reaches `main` is a combination **no run has ever compiled** — while every individual PR was legitimately green.

## It shipped today

Five PRs merged in fifteen seconds at 17:05:04–17:05:11. Main went red at 17:26:

```
memex/Memex.Portal.Shared/Api/MeshApiEndpoints.cs(335):
error CS0246: The type or namespace name 'MeshOperations' could not be found
```

A **semantic** conflict, so git had nothing to report and no merge was `DIRTY`:

- **#2283** moved `MeshOperations` to namespace `MeshWeaver.Mesh` and updated that call site's `using`.
- **#2397** restored the ORIGINAL namespace `MeshWeaver.AI`, because published modules reach the type through `[assembly: TypeForwardedTo]` and **a forwarder cannot rename**.

Each is correct. Each compiles against its own base. Only together do they fail. Fixed in #2411 (one `using`), but the *detection* is the issue: it surfaced from a scheduled main build ~20 minutes later, and it hard-blocks CD, which refuses a red tip. Today that sat directly in front of the surface-manifest image.

## Why the existing machinery does not cover it

- **`strict: false` is deliberate** and worth keeping — requiring every branch to re-sync before merge costs a full CI cycle per PR and, with several in flight, most of the throughput.
- **The green-tree marker / skip-reuse** makes it likelier, not less: a merge that reuses an already-green tree does not re-compile the combination either.
- **#2407** (binary-compat gate now blocking) does **not** catch this. That gate is about an already-published module binding a name; this is two source changes that disagree. Same family — *a green solo run proves less than it looks* — different mechanism. Worth stating plainly so nobody assumes it is covered.

## Options, roughly by cost

1. **A post-merge tripwire on `main` that is fast and loud.** Main already builds; the gap is *latency and attribution*. A compile-only job on every push to `main`, alerting with the failing file and `git log -S <symbol>` already run, turns a 20-minute silent window into a named alert. Cheapest, does not slow any PR, does not prevent the break.
2. **Re-test the merge result before it lands** — a merge queue, or `strict: true`. Actually prevents it; costs a cycle per merge and serialises the queue. That is the trade `strict: false` was chosen against, so this needs the maintainer, not a PR.
3. **Bound the burst.** Most of the risk is the fifteen-second window: merges close enough together that none saw the others. A minimum spacing, or "wait for main's run on your merge before the next", costs ~20 min per merge and is what we did manually today after the fact.

🚨 My recommendation is **(1) now, (2) as a maintainer decision** — and I want to be explicit that I am the one who created today's instance: I merged five PRs in fifteen seconds. The batching was sanctioned and each PR was sound; the burst is what made the untested combination. A tripwire that names the symbol would have caught it in ~2 minutes instead of 20, which is the difference between a footnote and a blocked deploy.

### PR DESCRIPTION
**Pull request by rbuergi**
Closes #2412.

## The defect

`dotnet-test.yml` set `cancel-in-progress: ${{ github.event_name != 'workflow_dispatch' }}`. Every push to main groups as `refs/heads/main`, so **each merge cancelled the run for the merge before it.**

Superseding is the right default on a PR branch — the later push tests a strict successor of what was killed, and that is where #2316's ~28% of runner demand is saved. On main the same setting loses two different things, and re-running later recovers neither:

1. **Nothing builds the combination that LANDED.** With `strict: false`, each PR is tested against the main it branched from — the *merged* tree is first compiled by main's own run. Cancel that and a semantic conflict between two independently-green PRs ships unbuilt. This is not hypothetical: five merges inside fifteen seconds put `CS0246: 'MeshOperations' could not be found` on main on 2026-08-26.
2. **Nothing publishes.** CD gates delivery on the required check `Consolidate test results` reaching `success` **for that SHA**. CD *does* still wake on a cancelled run — `main-cd.yml` subscribes with `types: [completed]` and cancelled counts as completed — it simply finds no success to act on.

Both failures are silent in this repo's characteristic way: a cancelled run and a run nobody needed look identical in the runs list, so "main is quiet" reads as healthy.

**Measured while writing this** — main's five consecutive runs, each cancelled by the next merge:

```
20:50:25  08d82de0  queued
20:38:39  444c6a9b  completed/cancelled
20:31:02  fe12f913  completed/cancelled
20:30:36  71e3ec2b  completed/cancelled
20:28:38  69916535  completed/cancelled
20:28:34  c5db4543  completed/cancelled
```

## The change

```diff
-  cancel-in-progress: ${{ github.event_name != 'workflow_dispatch' }}
+  cancel-in-progress: ${{ github.event_name != 'workflow_dispatch' && github.ref != 'refs/heads/main' }}
```

PR branches keep superseding. The cost is one full run per merge to main — which buys both the compile of what shipped and the ability to ship it.

`edge-images.yml` also sets `cancel-in-progress: true`, and is left alone deliberately: it is `workflow_dispatch`-only (its `push` trigger is commented out), so a newer manual edge build correctly supersedes an older one.

## The guard

`MainRunsAreNeverCancelledGuard` asserts on the *expression*, not a byte-exact line — any form that excludes `refs/heads/main` passes.

🚨 **Verified it can actually fail**, on both shapes a regression would take:

| negative control | result |
|---|---|
| the exact pre-fix line (`… != 'workflow_dispatch'`) | ❌ *"expression no longer excludes refs/heads/main"* |
| bare `cancel-in-progress: true` | ❌ *"sets cancel-in-progress: true unconditionally"* |

A comment cannot stop someone editing this line back to save runner minutes; a red test can.

## Verification

- `dotnet build -c Release -warnaserror` — `0 Error(s)`
- `MeshWeaver.Documentation.Test` — **70/70 passed**
- The What's New entry was validated **after a rebuild**: `Data/**` ships as `EmbeddedResource`, so the first `--no-build` run had checked the stale DLL, not the new file (DLL 23:01:12 > entry 22:57:54).

Also updates the AGENTS.md section that documented the cancellation as a standing fact — it would otherwise now be wrong — restating it as an invariant not to re-introduce.

### CODE REVIEW

File: test/MeshWeaver.Documentation.Test/MainRunsAreNeverCancelledGuard.cs [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+            + "(strict: false means the merged combination is first built by main's own run — this "
+            + "is how CS0246 reached main on 2026-08-26), and nothing publishes (CD gates on "
+            + "'Consolidate test results' reaching success for that SHA, which a cancelled run "
+            + "never produces). See #2412.");
+
+        Assert.True(value.Contains("refs/heads/main", StringComparison.Ordinal),
+            $"{Workflow}'s cancel-in-progress expression no longer excludes refs/heads/main: "
+            + $"'{value}'. Superseding is correct on a PR branch and wrong on main — a cancelled "
+            + "main run loses both the compile of the combination that shipped and the ability to "
+            + "ship it (#2412). Keep the ref check, or state in the expression why it is safe.");
```
[the remark this answers is not in the document]
Comment (rbuergi) [reply test/MeshWeaver.Documentation.Test/MainRunsAreNeverCancelledGuard.cs]: Correct, and thank you — that was a real hole. `${{ github.ref == 'refs/heads/main' }}` passed the substring check while cancelling on main, i.e. the exact inverse of the intent.

Fixed in d68407dc7 by making the guard **evaluate** the expression rather than match its spelling. `Evaluate` is a small recursive-descent evaluator for the slice of the GitHub expression language a `cancel-in-progress` value can use (`&&`, `||`, `!`, parentheses, `==`/`!=`, string literals, `true`/`false`, context lookups), with Actions' precedence and truthiness. Anything outside that subset throws rather than guessing — an unparseable expression must fail loudly, never silently evaluate to "fine".

Your counterexample is now a self-test row, and the assertion pins **both** halves of the intent: cancelling must be OFF for a push to `refs/heads/main`, and must stay ON for a `pull_request` run. The second half matters as much as the first — silently disabling superseding everywhere would hand back #2316's ~28% runner saving with nobody noticing, and the previous assertion could not see that either.

Verified RED on five shapes, each with the right message:

| expression | verdict |
|---|---|
| `${{ github.event_name != 'workflow_dispatch' }}` (pre-fix) | ❌ cancels on main |
| `true` | ❌ cancels on main |
| `${{ github.ref == 'refs/heads/main' }}` (**yours**) | ❌ cancels on main |
| `${{ … \|\| github.ref != 'refs/heads/main' }}` (disjunct) | ❌ cancels on main |
| `false` | ❌ no longer supersedes on PR branches |
